"""
config.py - Shared configuration, constants, and globals for issue_doctor.

All other modules import from here. issue_doctor.py (CLI) may mutate
OLLAMA_HOST, OLLAMA_MODEL, and EMBED_MODEL after parsing --model/--host/--embed.
"""

import os
from pathlib import Path

try:
    from rich.console import Console
    console = Console()
except ImportError:
    class _FallbackConsole:
        def print(self, *a, **kw): print(*a)
        def status(self, *a, **kw):
            import contextlib
            return contextlib.nullcontext()
    console = _FallbackConsole()

# ── Runtime-mutable globals (overridden by CLI flags) ─────────────────────────
OLLAMA_HOST  = os.environ.get("OLLAMA_HOST",  "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "qwen3:14b")
EMBED_MODEL  = os.environ.get("EMBED_MODEL",  "nomic-embed-text")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
SKILLS_DIR   = Path(os.environ.get("SKILLS_DIR", Path(__file__).parent / "skills"))

# ── Index configuration ────────────────────────────────────────────────────────
INDEX_DIR_NAME    = ".issue_doctor"
INDEX_DB_NAME     = "embeddings.db"
EMBED_DIMENSIONS  = 768
CHUNK_SIZE_LINES  = 60   # eval-optimised: medium-loose won (100% recall@10)
CHUNK_OVERLAP     = 20   # overlap=20 is the key factor vs overlap=10
TOP_K_CHUNKS      = 12
MAX_CONTEXT_CHARS = 16000

# ── File filtering ─────────────────────────────────────────────────────────────
INDEXABLE_EXTENSIONS = {
    ".c", ".cpp", ".cc", ".cxx", ".h", ".hpp",
    ".py", ".pyi", ".rs", ".go",
    ".js", ".ts", ".jsx", ".tsx",
    ".java", ".rb", ".swift", ".zig",
}

SKIP_DIRS = {
    ".git", ".github", ".issue_doctor", "node_modules", "__pycache__",
    ".mypy_cache", ".pytest_cache", "dist", "build", "target", ".build",
    "vendor", "third_party", "third-party", "thirdparty", "external",
    "contrib", ".venv", "venv", "env", ".env",
}

_TOOL_FILENAME = "issue_doctor.py"  # never index the tool itself

NOISE_DIRS = {
    "test", "tests", "unittest", "unittests",
    "docs", "doc", "examples", "example",
    "autogenerated", "generated", "bindings",
    "benchmarks", "benchmark",
}

# Documentation file detection — pattern-based, repo-agnostic
_DOC_NAME_PATTERNS = {
    "topics", "changelog", "changes", "news", "readme",
    "license", "authors", "credits", "history", "release",
    "pydoc", "locale", "translations", "i18n", "l10n",
    "generated", "autogenerated", "auto_generated",
    "reference", "glossary", "tutorial", "howto",
}

SOURCE_DIRS = {"lib", "src", "include"}

GENERIC_GOOD_PATHS = {
    "instcombine", "dagcombiner", "analysis", "transforms",
    "codegen", "sema", "parse", "ir",
}

PRIMARY_REPO_NAMES = {
    "llvm", "clang", "lld", "linux", "kernel", "webkit", "chromium"
}