#!/usr/bin/env python3
"""
issue_doctor.py - Local AI-powered GitHub issue bug diagnosis + draft patch.

Requires:
  pip install requests rich sqlite-vec

Requires Ollama:
  ollama pull qwen2.5-coder:14b
  ollama pull nomic-embed-text

Usage:
  python issue_doctor.py --url <github_url>
  python issue_doctor.py --url <url> --repo /path/to/repo
  python issue_doctor.py --url <url> --reindex
  python issue_doctor.py --url <url> --max-files 100
  python issue_doctor.py --diagnose
"""

import argparse
import json
import os
import re
import sqlite3
import struct
import sys
import time
from pathlib import Path
from typing import Optional

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

try:
    import requests
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Prompt
    from rich.rule import Rule
except ImportError:
    print("Missing dependencies. Run:  pip install requests rich sqlite-vec")
    sys.exit(1)

try:
    import sqlite_vec
    SQLITE_VEC_AVAILABLE = True
except ImportError:
    SQLITE_VEC_AVAILABLE = False

console = Console()

OLLAMA_HOST  = os.environ.get("OLLAMA_HOST",  "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "qwen3:14b")
EMBED_MODEL  = os.environ.get("EMBED_MODEL",  "nomic-embed-text")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
SKILLS_DIR   = Path(os.environ.get("SKILLS_DIR", Path(__file__).parent / "skills"))

INDEX_DIR_NAME   = ".issue_doctor"
INDEX_DB_NAME    = "embeddings.db"
EMBED_DIMENSIONS = 768
CHUNK_SIZE_LINES = 60   # eval-optimised: medium-loose won (100% recall@10)
CHUNK_OVERLAP    = 20   # overlap=20 is the key factor vs overlap=10
TOP_K_CHUNKS     = 12
MAX_CONTEXT_CHARS = 24000

INDEXABLE_EXTENSIONS = {
    ".c", ".cpp", ".cc", ".cxx", ".h", ".hpp",
    ".py", ".pyi", ".rs", ".go",
    ".js", ".ts", ".jsx", ".tsx",
    ".java", ".rb", ".swift", ".zig",
}

SKIP_DIRS = {
    ".git", ".github", ".issue_doctor", "node_modules", "__pycache__",
    ".mypy_cache", ".pytest_cache", "dist", "build", "target", ".build",
    "vendor", "third_party", "third-party", "thirdparty", "external",
    "contrib", ".venv", "venv", "env", ".env",
}
_TOOL_FILENAME = "issue_doctor.py"  # never index the tool itself

NOISE_DIRS = {
    "test", "tests", "unittest", "unittests",
    "docs", "doc", "examples", "example",
    "autogenerated", "generated", "bindings",
    "benchmarks", "benchmark",
}

# Documentation file detection — pattern-based, repo-agnostic
# These patterns identify documentation/data files that consume context
# budget without providing actionable source code for patches.
# Works across any repo without hardcoding project-specific names.
_DOC_NAME_PATTERNS = {
    "topics", "changelog", "changes", "news", "readme",
    "license", "authors", "credits", "history", "release",
    "pydoc", "locale", "translations", "i18n", "l10n",
    "generated", "autogenerated", "auto_generated",
    "reference", "glossary", "tutorial", "howto",
}

def is_doc_file(filepath: str) -> bool:
    """
    Returns True if the file looks like documentation rather than source.
    Pattern-based — works on any repo without hardcoded project names.
    """
    parts = filepath.lower().replace("\\", "/").split("/")
    stem = parts[-1].rsplit(".", 1)[0] if parts else ""
    # File stem matches a documentation pattern
    if any(pat in stem for pat in _DOC_NAME_PATTERNS):
        return True
    # Any directory component matches a documentation pattern
    if any(any(pat in part for pat in _DOC_NAME_PATTERNS)
           for part in parts[:-1]):
        return True
    return False

SOURCE_DIRS = {"lib", "src", "include"}

GENERIC_GOOD_PATHS = {
    "instcombine", "dagcombiner", "analysis", "transforms",
    "codegen", "sema", "parse", "ir",
}

PRIMARY_REPO_NAMES = {
    "llvm", "clang", "lld", "linux", "kernel", "webkit", "chromium"
}

# ── Vector helpers ────────────────────────────────────────────────────────────

def vec_to_blob(vec):
    return struct.pack(f"{len(vec)}f", *vec)

# ── Embedding ─────────────────────────────────────────────────────────────────

_EMBED_URL = ""
_EMBED_FORMAT = ""


def _detect_embed_api():
    global _EMBED_URL, _EMBED_FORMAT
    if _EMBED_URL:
        return _EMBED_URL, _EMBED_FORMAT
    candidates = [
        (f"{OLLAMA_HOST}/api/embed",      "new",  {"model": EMBED_MODEL, "input": ["test"]}),
        (f"{OLLAMA_HOST}/api/embed",      "new1", {"model": EMBED_MODEL, "input": "test"}),
        (f"{OLLAMA_HOST}/api/embeddings", "old",  {"model": EMBED_MODEL, "prompt": "test"}),
    ]
    for url, fmt, payload in candidates:
        try:
            r = requests.post(url, json=payload, timeout=15)
            if r.status_code == 200:
                data = r.json()
                if "embeddings" in data or "embedding" in data:
                    _EMBED_URL, _EMBED_FORMAT = url, fmt
                    console.print(f"[dim]Embed API: {url} ({fmt})[/]")
                    return url, fmt
        except Exception:
            continue
    console.print("[red]Could not detect working Ollama embed API.[/]")
    return "", ""


def embed_texts(texts):
    if not texts:
        return []
    url, fmt = _detect_embed_api()
    if not url:
        return [[] for _ in texts]
    try:
        if fmt == "new":
            resp = requests.post(url, json={"model": EMBED_MODEL, "input": texts},
                                 timeout=max(30, len(texts) * 2))
            if resp.status_code == 200:
                return resp.json().get("embeddings", [[] for _ in texts])
        results = []
        for t in texts:
            if fmt == "new1":
                resp = requests.post(url, json={"model": EMBED_MODEL, "input": t}, timeout=30)
                if resp.status_code == 200:
                    embs = resp.json().get("embeddings", [[]])
                    results.append(embs[0] if embs else [])
                else:
                    results.append([])
            else:
                resp = requests.post(url, json={"model": EMBED_MODEL, "prompt": t}, timeout=30)
                results.append(resp.json().get("embedding", []) if resp.status_code == 200 else [])
        return results
    except Exception as e:
        console.print(f"[red]Embedding failed: {e}[/]")
        return [[] for _ in texts]


def embed_single(text):
    r = embed_texts([text])
    return r[0] if r else []

# ── File scoring ──────────────────────────────────────────────────────────────

def extract_keywords_from_issue(issue_text):
    cleaned = re.sub(r"https?://\S+", "", issue_text)
    cleaned = re.sub(r"```.*?```", "", cleaned, flags=re.DOTALL)
    words = re.findall(r"\b([a-zA-Z_]\w{3,})\b", cleaned)
    stopwords = {"this","that","with","from","have","when","where","which",
                 "there","their","about","would","could","should","will",
                 "also","more","than","then","into"}
    seen, result = set(), []
    for w in words:
        wl = w.lower()
        if wl not in stopwords and wl not in seen:
            seen.add(wl); result.append(wl)
    return result[:80]


def score_file(filepath, repo_root, all_kws):
    if filepath.name == _TOOL_FILENAME:
        return -1  # never index the tool itself
    path_lower = str(filepath).lower().replace("\\", "/")
    parts = set(path_lower.replace(str(repo_root).lower().replace("\\","/"), "").split("/"))
    name = filepath.name.lower()
    stem = filepath.stem.lower()

    if parts & NOISE_DIRS:
        return -1

    source_boost  = 3 if parts & SOURCE_DIRS else 0
    primary_boost = 2 if any(name_part in path_lower.split("/")[0]
                              for name_part in PRIMARY_REPO_NAMES) else 0
    issue_hits    = sum(3 for kw in all_kws if len(kw) > 4 and (kw in name or kw in stem))
    path_hits     = sum(1 for kw in all_kws if len(kw) > 4 and kw in path_lower)
    generic_hits  = len(parts & GENERIC_GOOD_PATHS)

    return source_boost + primary_boost + issue_hits + path_hits + generic_hits

# ── Chunking ──────────────────────────────────────────────────────────────────

def chunk_file(filepath, repo_root):
    try:
        text = filepath.read_text(encoding="utf-8", errors="ignore")
    except (OSError, PermissionError):
        return []
    lines = text.splitlines()
    if not lines:
        return []
    rel = str(filepath.relative_to(repo_root)).replace("\\", "/")
    func_pattern = re.compile(
        r"^(?:pub\s+)?(?:static\s+)?(?:inline\s+)?(?:async\s+)?"
        r"(?:def |fn |func |function |class |\w[\w\s\*:<>&,]*\s+\w+\s*\()"
    )
    # C/C++ multi-line function signatures: detect lines that look like
    # function names followed by ( on the same line OR the next line
    # e.g. "find_frozen(PyObject *name" or "PyImport_ImportModule("
    c_func_pattern = re.compile(
        # C function definitions: identifier( with no semicolon
        # Excludes control flow: if/for/while/switch/return etc.
        r"^(?!(?:if|for|while|switch|return|else|do|case|break|continue|goto)\b)"
        r"[A-Za-z_][\w]*\s*\([^;]*$"
    )
    # Choose pattern based on file extension
    is_c_file = filepath.suffix in {'.c', '.h'}
    boundaries = [0]
    for i, line in enumerate(lines):
        if i > 0:
            stripped = line.strip()
            if func_pattern.match(stripped):
                boundaries.append(i)
            elif is_c_file and c_func_pattern.match(stripped):
                boundaries.append(i)
    boundaries.append(len(lines))
    chunks = []
    if len(boundaries) > 2:
        for idx in range(len(boundaries) - 1):
            start = max(0, boundaries[idx] - CHUNK_OVERLAP)
            end   = boundaries[idx + 1]
            content = "\n".join(
                "{:4d}  {}".format(start + k + 1, l)
                for k, l in enumerate(lines[start:end])
            )
            chunks.append({"filepath": rel, "start_line": start+1,
                           "end_line": end, "content": content})
    else:
        i = 0
        while i < len(lines):
            end = min(i + CHUNK_SIZE_LINES, len(lines))
            content = "\n".join(
                "{:4d}  {}".format(i+k+1, l) for k, l in enumerate(lines[i:end])
            )
            chunks.append({"filepath": rel, "start_line": i+1,
                           "end_line": end, "content": content})
            i += CHUNK_SIZE_LINES - CHUNK_OVERLAP
    return chunks

# ── Index management ──────────────────────────────────────────────────────────

def get_index_path(repo_root):
    return repo_root / INDEX_DIR_NAME / INDEX_DB_NAME


def open_index(index_path, create=False):
    if not SQLITE_VEC_AVAILABLE:
        return None
    if not create and not index_path.exists():
        return None
    index_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(index_path))
    conn.enable_load_extension(True)
    sqlite_vec.load(conn)
    conn.enable_load_extension(False)
    return conn


def init_index_schema(conn):
    conn.executescript(f"""
        CREATE TABLE IF NOT EXISTS chunks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            filepath TEXT NOT NULL,
            start_line INTEGER NOT NULL,
            end_line INTEGER NOT NULL,
            content TEXT NOT NULL
        );
        CREATE VIRTUAL TABLE IF NOT EXISTS chunk_embeddings
        USING vec0(embedding FLOAT[{EMBED_DIMENSIONS}]);
        CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, value TEXT);
        CREATE TABLE IF NOT EXISTS dir_keywords (
            directory TEXT NOT NULL,
            keyword   TEXT NOT NULL,
            weight    INTEGER NOT NULL DEFAULT 1
        );
        CREATE INDEX IF NOT EXISTS idx_dir_kw ON dir_keywords(keyword);
        CREATE TABLE IF NOT EXISTS dir_activity (
            directory    TEXT PRIMARY KEY,
            commit_count INTEGER NOT NULL DEFAULT 0,
            last_commit  TEXT
        );
        CREATE TABLE IF NOT EXISTS file_versions (
            filepath     TEXT PRIMARY KEY,
            commit_hash  TEXT NOT NULL,
            indexed_at   TEXT NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_fv_filepath ON file_versions(filepath);
    """)
    conn.commit()


def get_repo_commit_hash(repo_root):
    try:
        head = (repo_root / ".git" / "HEAD").read_text().strip()
        if head.startswith("ref: "):
            ref_path = repo_root / ".git" / head[5:]
            if ref_path.exists():
                return ref_path.read_text().strip()[:12]
        return head[:12]
    except Exception:
        return "unknown"


def get_file_commit_hash(repo_root: Path, filepath: Path) -> str:
    """Get the most recent commit hash that touched a specific file."""
    import subprocess
    try:
        rel = str(filepath.relative_to(repo_root)).replace("\\", "/")
        result = subprocess.run(
            ["git", "log", "--format=%H", "-1", "--", rel],
            capture_output=True, text=True,
            cwd=str(repo_root), timeout=10
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()[:12]
    except Exception:
        pass
    return "unknown"


def get_file_commit_hashes_batch(repo_root: Path, filepaths: list) -> dict:
    """
    Get commit hashes for multiple files in one git log call.
    Much faster than calling git once per file.
    Returns {filepath_str: commit_hash}.
    """
    import subprocess
    if not filepaths:
        return {}

    try:
        # Use git log with --name-only to get last commit per file efficiently
        result = subprocess.run(
            ["git", "log", "--format=%H", "--name-only", "--diff-filter=AM",
             "-5000"],  # look back far enough to cover all indexed files
            capture_output=True, text=True,
            cwd=str(repo_root), timeout=60
        )
        if result.returncode != 0:
            return {}

        # Build map: filepath -> first (most recent) commit that touched it
        file_to_hash: dict[str, str] = {}
        current_hash = ""
        for line in result.stdout.splitlines():
            line = line.strip()
            if not line:
                continue
            if len(line) == 40 and all(c in "0123456789abcdef" for c in line):
                current_hash = line[:12]
            elif current_hash and "/" in line:
                norm = line.replace("\\", "/")
                if norm not in file_to_hash:
                    file_to_hash[norm] = current_hash

        # Match against our filepaths
        result_map = {}
        for fp in filepaths:
            rel = str(fp.relative_to(repo_root)).replace("\\", "/")
            result_map[rel] = file_to_hash.get(rel, "unknown")
        return result_map

    except Exception:
        return {}


def index_is_fresh(conn, repo_root):
    try:
        row = conn.execute("SELECT value FROM meta WHERE key='commit_hash'").fetchone()
        return row and row[0] == get_repo_commit_hash(repo_root)
    except Exception:
        return False


def get_stale_files(conn, repo_root: Path, filepaths: list) -> tuple[list, list]:
    """
    Given a list of file paths, return (new_files, changed_files).
    - new_files: not yet in the index at all
    - changed_files: in the index but with a different commit hash

    Uses batch git log for efficiency.
    """
    if not filepaths:
        return [], []

    # Get current commit hashes for all files in one git call
    current_hashes = get_file_commit_hashes_batch(repo_root, filepaths)

    # Get stored hashes from the index
    stored = {}
    try:
        rows = conn.execute(
            "SELECT filepath, commit_hash FROM file_versions"
        ).fetchall()
        stored = {r[0]: r[1] for r in rows}
    except Exception:
        pass

    new_files = []
    changed_files = []
    for fp in filepaths:
        rel = str(fp.relative_to(repo_root)).replace("\\", "/")
        current = current_hashes.get(rel, "unknown")
        if rel not in stored:
            new_files.append(fp)
        elif stored[rel] != current:
            changed_files.append(fp)

    return new_files, changed_files


# ── Git activity map ──────────────────────────────────────────────────────────

def build_git_activity_map(repo_root: Path, conn: sqlite3.Connection,
                            months: int = 6) -> None:
    """
    Build a directory activity map from git history.
    For each directory, count how many commits touched files in it
    over the last N months. Store in dir_activity table.

    This is repo-agnostic — every git repo has this signal regardless
    of language, naming convention, or project structure.
    Directories with more recent commits are more likely to be
    active development areas and therefore likely fix locations.
    """
    import subprocess
    import math

    console.print(f"[dim]  Building git activity map ({months} months)...[/]")

    # Run git log to get all files changed in the period
    # --name-only gives one filepath per line, blank lines between commits
    # --format= suppresses commit headers
    try:
        result = subprocess.run(
            [
                "git", "log",
                f"--since={months} months ago",
                "--name-only",
                "--format=",
                "--diff-filter=AM",   # Added or Modified only
            ],
            capture_output=True,
            text=True,
            cwd=str(repo_root),
            timeout=60,
        )
        if result.returncode != 0:
            console.print(f"[dim]  git log failed: {result.stderr[:80]}[/]")
            return
    except (subprocess.TimeoutExpired, FileNotFoundError) as e:
        console.print(f"[dim]  git not available: {e}[/]")
        return

    # Count commits per directory
    dir_commits: dict[str, int] = {}
    for line in result.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        # Normalise to forward slashes
        path = line.replace("\\", "/")
        # Get the directory component
        if "/" in path:
            directory = "/".join(path.split("/")[:-1])
        else:
            directory = "."
        # Also credit parent directories (activity bubbles up)
        parts = directory.split("/")
        for depth in range(1, len(parts) + 1):
            parent = "/".join(parts[:depth])
            dir_commits[parent] = dir_commits.get(parent, 0) + 1

    if not dir_commits:
        console.print("[dim]  No git activity found[/]")
        return

    # Normalise: convert raw counts to log scale for storage
    # Store raw counts — we apply log at query time
    conn.execute("DELETE FROM dir_activity")
    rows = [(d, c) for d, c in dir_commits.items()]
    conn.executemany(
        "INSERT OR REPLACE INTO dir_activity (directory, commit_count) "
        "VALUES (?, ?)",
        rows
    )
    conn.commit()

    total_dirs = len(dir_commits)
    max_commits = max(dir_commits.values()) if dir_commits else 0
    console.print(
        f"[dim]  Git activity: {total_dirs} dirs, "
        f"max {max_commits} file-changes in top dir[/]"
    )



# ── Directory auto-discovery ──────────────────────────────────────────────────

def build_dir_keyword_map(repo_root: Path, conn: sqlite3.Connection) -> None:
    """
    Build a directory keyword map from the repo's own structure.
    For each directory containing source files, extract keywords from:
      - the directory path components
      - the stems of all source filenames in that directory
    Store in the index DB for use at query time.
    No embedding required — pure string analysis.
    """
    console.print("[dim]  Building directory keyword map...[/]")

    conn.executescript("""
        CREATE TABLE IF NOT EXISTS dir_keywords (
            directory TEXT NOT NULL,
            keyword   TEXT NOT NULL,
            weight    INTEGER NOT NULL DEFAULT 1
        );
        CREATE INDEX IF NOT EXISTS idx_dir_kw ON dir_keywords(keyword);
        CREATE TABLE IF NOT EXISTS dir_activity (
            directory    TEXT PRIMARY KEY,
            commit_count INTEGER NOT NULL DEFAULT 0,
            last_commit  TEXT
        );
        DELETE FROM dir_keywords;
    """)

    dir_keywords: dict[str, set[str]] = {}

    for f in repo_root.rglob("*"):
        try:
            if not f.is_file():
                continue
        except (OSError, PermissionError):
            continue
        if f.suffix not in INDEXABLE_EXTENSIONS:
            continue
        if any(part in SKIP_DIRS for part in f.parts):
            continue

        rel = str(f.relative_to(repo_root)).replace("\\", "/")
        # Directory is everything up to the filename
        dir_path = "/".join(rel.split("/")[:-1])
        if not dir_path:
            dir_path = "."

        if dir_path not in dir_keywords:
            dir_keywords[dir_path] = set()

        # Add keywords from directory path components
        for part in dir_path.split("/"):
            if len(part) >= 3:
                # Split CamelCase: InstCombine -> inst, combine, instcombine
                tokens = _tokenise_identifier(part)
                dir_keywords[dir_path].update(tokens)

        # Add keywords from the filename stem
        stem = f.stem
        tokens = _tokenise_identifier(stem)
        dir_keywords[dir_path].update(tokens)

    # Write to DB — store dir path tokens and file tokens separately
    # Dir path tokens (weight=3): strong signal — the dir IS called InstCombine
    # File name tokens (weight=1): weaker signal — file implements the feature
    rows = []
    for directory, keywords in dir_keywords.items():
        # Separate dir-path tokens from file tokens
        dir_tokens = set()
        for part in directory.split("/"):
            if len(part) >= 3:
                dir_tokens.update(tok.lower() for tok in _tokenise_identifier(part))

        for kw in keywords:
            kw_lower = kw.lower()
            if len(kw_lower) < 3:
                continue
            weight = 3 if kw_lower in dir_tokens else 1
            rows.append((directory, kw_lower, weight))

    conn.executemany(
        "INSERT INTO dir_keywords (directory, keyword, weight) VALUES (?, ?, ?)",
        rows
    )
    conn.commit()
    console.print(f"[dim]  Dir keyword map: {len(dir_keywords)} directories, "
                  f"{len(rows)} keyword entries[/]")


def _tokenise_identifier(name: str) -> list[str]:
    """
    Split an identifier into keyword tokens.
    InstCombineCasts -> [instcombinecasts, inst, combine, casts, instcombine]
    loop_vectorize  -> [loop, vectorize, loop_vectorize]
    CGBuiltin       -> [cgbuiltin, cg, builtin]
    """
    tokens = [name.lower()]  # always include the full name

    # Split on underscores and hyphens
    parts = re.split(r'[_\-]', name)
    tokens.extend(p.lower() for p in parts if len(p) >= 3)

    # Split CamelCase
    camel_parts = re.findall(r'[A-Z]?[a-z]+|[A-Z]+(?=[A-Z]|$)', name)
    tokens.extend(p.lower() for p in camel_parts if len(p) >= 3)

    # Also add pairs of consecutive camel parts
    for i in range(len(camel_parts) - 1):
        pair = camel_parts[i].lower() + camel_parts[i+1].lower()
        if len(pair) >= 5:
            tokens.append(pair)

    return list(set(tokens))


def get_guaranteed_dirs_from_map(
    issue_text: str,
    skill_keywords: list[str],
    conn: sqlite3.Connection,
    repo_root: Path,
    top_n_dirs: int = 12,
) -> list[Path]:
    """
    Query the directory keyword map to find which directories
    are most relevant to this issue.
    Returns list of directory Paths to force-include in the index.
    """
    # Check if the map exists
    try:
        count = conn.execute("SELECT COUNT(*) FROM dir_keywords").fetchone()[0]
        if count == 0:
            return []
    except Exception:
        return []

    # Extract keywords from the issue
    from_issue = extract_keywords_from_issue(issue_text) if issue_text else []
    all_kws_raw = list(dict.fromkeys(
        [k.lower() for k in (from_issue + skill_keywords)]
    ))[:60]

    # Use SPECIFIC identifiers only for directory matching.
    # Generic words (float, cast, calls, convert) appear in thousands of
    # directories and produce noise. We require min 6 chars to filter them out.
    # This ensures AMDGPU (which handles float/cast/calls) doesn't outscore
    # InstCombine (which specifically matches 'instcombine').
    GENERIC_NOISE = {
        'float', 'calls', 'convert', 'conversion', 'integer', 'value',
        'values', 'target', 'function', 'pointer', 'offset', 'result',
        'source', 'output', 'input', 'object', 'optimize', 'missed',
        'expressions', 'expression', 'pattern', 'optimization', 'failed',
        'issue', 'error', 'should', 'return', 'using', 'check',
    }
    specific_kws = [
        k for k in all_kws_raw
        if len(k) >= 6 and k not in GENERIC_NOISE
    ]

    if not specific_kws:
        # Fall back to all keywords if nothing specific found
        specific_kws = [k for k in all_kws_raw if len(k) >= 4]

    # Score each directory using weighted keyword matches:
    # weight=3 if keyword matches directory path name (strong signal)
    # weight=1 if keyword matches only a filename in the dir (weaker signal)
    dir_scores: dict[str, float] = {}
    for kw in specific_kws:
        rows = conn.execute(
            "SELECT directory, weight FROM dir_keywords WHERE keyword = ?",
            (kw,)
        ).fetchall()
        for (directory, weight) in rows:
            dir_scores[directory] = dir_scores.get(directory, 0) + weight

    if not dir_scores:
        return []

    # Filter out noise directories
    noise = NOISE_DIRS | {"include"}  # headers alone aren't enough
    filtered = {
        d: s for d, s in dir_scores.items()
        if not any(part in noise for part in d.split("/"))
        and s >= 1  # require at least 1 keyword match
    }

    # Combine keyword score with git activity signal
    # final_score = keyword_matches * log(1 + recent_commits)
    #
    # This is repo-agnostic: no hardcoded directory names or penalties.
    # Active directories float up naturally because they have both
    # keyword relevance AND recent commit activity.
    import math

    # Load git activity for all matched directories
    dir_activity: dict[str, int] = {}
    try:
        matched_dirs = list(filtered.keys())
        if matched_dirs:
            placeholders = ",".join("?" * len(matched_dirs))
            rows = conn.execute(
                f"SELECT directory, commit_count FROM dir_activity "
                f"WHERE directory IN ({placeholders})",
                matched_dirs
            ).fetchall()
            dir_activity = {r[0]: r[1] for r in rows}
    except Exception:
        pass  # dir_activity table may not exist yet — degrade gracefully

    # Score = keyword_matches * log(1 + commits)
    # If no activity data: score = keyword_matches * 1.0 (neutral)
    final_scores: dict[str, float] = {}
    for d, kw_score in filtered.items():
        commits = dir_activity.get(d, 0)
        # Cap commits to prevent mega-active dirs (AMDGPU: 2240) from
        # dominating over focused dirs (InstCombine: ~150).
        # 500 commit cap means log(501)=6.2 vs log(151)=5.0 — reasonable gap
        # without letting raw activity overwhelm keyword relevance.
        capped_commits = min(commits, 500)
        activity_factor = math.log(1 + capped_commits) if capped_commits > 0 else 1.0
        # Square kw_score so keyword relevance is the primary signal
        # A dir with kw=3 beats kw=1 by 9x, not 3x — specificity matters more
        final_scores[d] = (kw_score ** 2) * activity_factor

    top_dirs = sorted(
        final_scores.items(), key=lambda x: x[1], reverse=True
    )[:top_n_dirs]

    if top_dirs:
        console.print("[dim]  Auto-discovered relevant directories:[/]")
        for d, score in top_dirs:
            kw = filtered.get(d, 0)
            commits = dir_activity.get(d, 0)
            console.print(
                f"[dim]    {d} "
                f"(kw={kw}, commits={commits}, score={score:.1f})[/]"
            )

    return [repo_root / d.replace("/", os.sep) for d, _ in top_dirs]



def build_index(repo_root, conn, force=False, max_index_files=3000,
                issue_text="", skill_keywords=None):
    import datetime
    if skill_keywords is None:
        skill_keywords = []

    # Check if we can do an incremental update instead of full rebuild
    has_existing = False
    try:
        count = conn.execute("SELECT COUNT(*) FROM chunks").fetchone()[0]
        has_existing = count > 0
    except Exception:
        pass

    if not force and index_is_fresh(conn, repo_root) and has_existing:
        console.print("[dim]Index is up to date.[/]")
        return

    # Decide: full rebuild or incremental update?
    current_hash = get_repo_commit_hash(repo_root)
    incremental = has_existing and not force

    if incremental:
        console.print("[bold cyan]Updating RAG index incrementally...[/]")
        console.print("[dim]Checking which files changed since last index...[/]")
    else:
        console.print("[bold cyan]Building RAG index...[/]")
        console.print("[dim]This runs once per repo. Subsequent runs use the cache.[/]")
        # Full rebuild: drop and recreate
        conn.executescript("""
            DELETE FROM chunks;
            DELETE FROM chunk_embeddings;
            DELETE FROM meta;
            DROP TABLE IF EXISTS dir_keywords;
            DROP TABLE IF EXISTS dir_activity;
            DROP TABLE IF EXISTS file_versions;
        """)
        conn.commit()
        init_index_schema(conn)

    # Collect files
    all_files = []
    for f in repo_root.rglob("*"):
        try:
            is_file = f.is_file()
        except (OSError, PermissionError):
            continue
        if is_file and f.suffix in INDEXABLE_EXTENSIONS:
            if any(part in SKIP_DIRS for part in f.parts):
                continue
            all_files.append(f)

    console.print(f"[dim]  {len(all_files)} indexable files found[/]")

    # Issue-aware pre-filtering
    issue_kws = set(extract_keywords_from_issue(issue_text)) if issue_text else set()
    all_kws = {k.lower() for k in (issue_kws | set(skill_keywords))}

    if len(all_files) > max_index_files:
        console.print(f"[dim]  Pre-filtering to top {max_index_files} most relevant files...[/]")

        # Step 1: Build directory maps from repo structure (Option 2 + git)
        # These run once and are cached in the index — no hardcoded paths needed
        build_git_activity_map(repo_root, conn)   # git history signal
        build_dir_keyword_map(repo_root, conn)    # filename/dirname keywords

        # Step 2: Auto-discover relevant directories from the map
        auto_dirs = get_guaranteed_dirs_from_map(
            issue_text, skill_keywords or [], conn, repo_root, top_n_dirs=12
        )

        # Step 3: Collect files from auto-discovered directories
        guaranteed_files = []
        seen_guaranteed = set()
        for dir_path in auto_dirs:
            if not dir_path.exists():
                continue
            for f in dir_path.rglob("*"):
                try:
                    is_file = f.is_file()
                except (OSError, PermissionError):
                    continue
                rel_str = str(f.relative_to(repo_root)).replace("\\", "/")
                if (is_file
                        and f.suffix in INDEXABLE_EXTENSIONS
                        and f not in seen_guaranteed
                        and not any(
                            any(nd in p.lower() for nd in NOISE_DIRS)
                            for p in f.parts
                        )
                        and f.name != _TOOL_FILENAME
                        and not is_doc_file(rel_str)):
                    seen_guaranteed.add(f)
                    guaranteed_files.append(f)

        if guaranteed_files:
            console.print(
                f"[dim]  Auto-guaranteed {len(guaranteed_files)} files "
                f"from {len(auto_dirs)} directories[/]"
            )

        # Step 4: Score remaining files and fill up to max_index_files
        guaranteed_set = set(guaranteed_files)
        remaining = [f for f in all_files if f not in guaranteed_set]
        remaining_sorted = sorted(
            remaining,
            key=lambda f: score_file(f, repo_root, all_kws),
            reverse=True
        )
        slots_left = max(0, max_index_files - len(guaranteed_files))
        scored_files = [f for f in remaining_sorted[:slots_left]
                        if score_file(f, repo_root, all_kws) >= 0]

        all_files = guaranteed_files + scored_files

        # Show top scored files for transparency
        console.print("[dim]  Top scored files:[/]")
        for f in remaining_sorted[:5]:
            rel = str(f.relative_to(repo_root)).replace("\\", "/")
            s = score_file(f, repo_root, all_kws)
            console.print(f"[dim]    {rel} (score={s})[/]")

    console.print(f"[dim]  Indexing {len(all_files)} files[/]")

    # For incremental: only process new/changed files
    if incremental:
        new_files, changed_files = get_stale_files(conn, repo_root, all_files)
        files_to_process = new_files + changed_files
        if not files_to_process:
            console.print('[green]All indexed files are up to date.[/]')
            conn.execute("INSERT OR REPLACE INTO meta VALUES ('commit_hash',?)",
                         (current_hash,))
            conn.commit()
            return
        console.print(
            f'[dim]  {len(new_files)} new, {len(changed_files)} changed files[/]'
        )
        # Remove old chunks for changed files
        for f in changed_files:
            rel = str(f.relative_to(repo_root)).replace("\\", "/")
            old_ids = [r[0] for r in conn.execute(
                "SELECT id FROM chunks WHERE filepath=?", (rel,)
            ).fetchall()]
            if old_ids:
                ph = ",".join("?" * len(old_ids))
                conn.execute(f"DELETE FROM chunk_embeddings WHERE rowid IN ({ph})",
                             old_ids)
                conn.execute("DELETE FROM chunks WHERE filepath=?", (rel,))
            conn.execute("DELETE FROM file_versions WHERE filepath=?", (rel,))
        conn.commit()
    else:
        files_to_process = all_files

    # Chunk
    all_chunks = []
    for f in files_to_process:
        all_chunks.extend(chunk_file(f, repo_root))

    if all_chunks:
        console.print(f'[dim]  {len(all_chunks)} chunks to embed[/]')
    else:
        console.print('[dim]  No new chunks to embed.[/]')

    # Embed in batches
    BATCH_SIZE   = 16
    COMMIT_EVERY = 100
    total_embedded = 0
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    file_hashes = get_file_commit_hashes_batch(repo_root, files_to_process)

    for batch_start in range(0, len(all_chunks), BATCH_SIZE):
        batch = all_chunks[batch_start:batch_start + BATCH_SIZE]
        texts = [c["content"][:1000] for c in batch]
        embeddings = embed_texts(texts)

        for chunk, emb in zip(batch, embeddings):
            if not emb or len(emb) != EMBED_DIMENSIONS:
                continue
            cur = conn.execute(
                "INSERT INTO chunks (filepath, start_line, end_line, content) VALUES (?,?,?,?)",
                (chunk["filepath"], chunk["start_line"],
                 chunk["end_line"], chunk["content"])
            )
            conn.execute(
                "INSERT INTO chunk_embeddings (rowid, embedding) VALUES (?,?)",
                (cur.lastrowid, vec_to_blob(emb))
            )
            total_embedded += 1

        if total_embedded % COMMIT_EVERY == 0:
            conn.commit()

        if all_chunks:
            pct = 100 * min(batch_start + BATCH_SIZE, len(all_chunks)) // len(all_chunks)
            console.print(
                f'[dim]  {total_embedded}/{len(all_chunks)} embedded ({pct}%)...[/]',
                end='\r'
            )

    conn.commit()

    # Record file versions
    for f in files_to_process:
        rel = str(f.relative_to(repo_root)).replace("\\", "/")
        conn.execute(
            "INSERT OR REPLACE INTO file_versions (filepath, commit_hash, indexed_at) "
            "VALUES (?, ?, ?)",
            (rel, file_hashes.get(rel, 'unknown'), now)
        )

    total_now = conn.execute("SELECT COUNT(*) FROM chunks").fetchone()[0]
    conn.execute("INSERT OR REPLACE INTO meta VALUES ('commit_hash',?)",
                 (current_hash,))
    conn.execute("INSERT OR REPLACE INTO meta VALUES ('total_chunks',?)",
                 (str(total_now),))
    conn.commit()

    if incremental and total_embedded > 0:
        console.print(
            f'\n[green]Index updated: {total_embedded} chunks re-embedded, '
            f'{total_now} total[/]'
        )
    elif not incremental:
        console.print(f'\n[green]Index built: {total_embedded} chunks embedded[/]')


# ── Query augmentation ───────────────────────────────────────────────────────

def augment_query(issue_text: str, skill_keywords: list) -> tuple[str, list[str]]:
    """
    Extract high-signal technical identifiers from issue text.
    Returns (augmented_query, keywords_list).
    """
    identifiers = []

    # 1. Extract from issue title (first line) — title tokens are very high signal
    first_line = issue_text.split('\n')[0]
    title_tokens = re.findall(r'\b([A-Za-z_]\w{3,})\b', first_line)
    identifiers.extend(title_tokens)

    # 2. Backtick-quoted content — split into individual tokens
    # Use generous length limit, then tokenize the contents
    backtick_contents = re.findall(r'`([^`]{2,300})`', issue_text)
    for bc in backtick_contents:
        # Short backtick content: use as-is (likely a single identifier)
        if len(bc) <= 60 and ' ' not in bc:
            identifiers.append(bc)
        # Long content: tokenize into individual identifiers
        tokens = re.findall(r'\b([A-Za-z_]\w{2,})\b', bc)
        identifiers.extend(tokens)

    # 3. CamelCase identifiers (2+ humps)
    camel = re.findall(r'\b([A-Z][a-z]+(?:[A-Z][a-z]*)+\w*)\b', issue_text)
    identifiers.extend(camel)

    # 4. ALL_CAPS macros/constants (INT32_MAX, UINT32_MAX etc.)
    macros = re.findall(r'\b([A-Z][A-Z0-9_]{3,})\b', issue_text)
    identifiers.extend(macros)

    # 5. Function call patterns: word()
    func_calls = re.findall(r'\b(\w{4,})\s*\(', issue_text)
    identifiers.extend(func_calls)

    # 6. LLVM/compiler intrinsic names: @llvm.fptosi.sat -> extract parts
    # Intrinsic name parts bypass the structural filter — they are always
    # specific identifiers regardless of length (fptosi, fptoui, sat etc.)
    intrinsic_parts = []
    intrinsics = re.findall(r'@(llvm\.\w+(?:\.\w+)*)', issue_text)
    for intr in intrinsics:
        identifiers.append(intr)
        parts = intr.split('.')
        intrinsic_parts.extend(parts[1:])  # skip 'llvm', keep fptosi/fptoui/sat
    # Also check labels for subsystem names (e.g. llvm:instcombine)
    label_ids = re.findall(r'llvm:([a-z][a-z0-9]+)', issue_text.lower())
    intrinsic_parts.extend(label_ids)  # instcombine, optimizations, etc.

    # 7. File path fragments
    paths = re.findall(r'\b(\w+/\w+(?:/\w+)*\.\w+)\b', issue_text)
    identifiers.extend(paths)

    # 8. Error message quoted strings
    quoted = re.findall(r'"([^"]{5,60})"', issue_text)
    for q in quoted:
        tokens = re.findall(r'\b(\w{4,})\b', q)
        identifiers.extend(tokens)

    # Deduplicate preserving order, filter noise
    # Structural identifier filter — language and project agnostic.
    # A code identifier worth searching for has one of these shapes:
    #   - Contains underscore:  find_frozen, PyUnicode_AsUTF8, INT32_MAX
    #   - CamelCase (2+ humps): MemoryBuiltins, InstCombineCasts
    #   - ALL_CAPS macro:       INT32_MAX, UINT32_MAX
    #   - Long enough to be specific (>= 8 chars for plain words)
    #
    # We reject: short common words, language keywords, project names,
    # GitHub issue boilerplate — all structurally, not by enumeration.

    # Small set of universal stopwords that would never be useful
    # code search terms regardless of language or project
    UNIVERSAL_STOP = {
        # GitHub issue template boilerplate
        'repository', 'branch', 'version', 'tested', 'operating',
        'systems', 'linked', 'report', 'description', 'reproducer',
        'expected', 'actual', 'behavior', 'behaviour', 'output',
        # Universal programming noise (too generic in any codebase)
        'function', 'method', 'class', 'object', 'variable',
        'pointer', 'buffer', 'memory', 'address', 'offset',
        'error', 'result', 'value', 'return', 'nullptr', 'null',
    }

    def is_code_identifier(token: str) -> bool:
        """
        Returns True if token looks like a specific code identifier
        worth searching for, using structural rules only.
        Works for C, C++, Python, Rust, Go, Java — any language.
        """
        if not token or token.isdigit():
            return False
        t = token.strip()
        tl = t.lower()
        if tl in UNIVERSAL_STOP:
            return False
        # Must be at least 5 chars to avoid single-word noise
        if len(t) < 5:
            return False
        # File paths (contain /) are always useful
        if '/' in t or '\\' in t:
            return True
        # Contains underscore → almost certainly a code identifier
        if '_' in t:
            return True
        # CamelCase with 2+ humps
        if re.search(r'[a-z][A-Z]', t):
            return True
        # ALL_CAPS (already caught by underscore, but belt+suspenders)
        if t.isupper() and len(t) >= 5:
            return True
        # Long enough to be a specific term (not a common English word)
        # Threshold of 11 filters: saturated(9), conversion(10), frozen(6)
        # Keeps: instcombine(11), optimization(12), vectorize(10->drops, ok)
        # Note: importlib(9) drops here but is caught by other rules upstream
        if len(t) >= 11 and t.isalpha():
            return True
        return False

    seen = set()
    clean = []
    for ident in identifiers:
        norm = ident.strip()
        if norm and norm not in seen and is_code_identifier(norm):
            seen.add(norm)
            clean.append(norm)

    # Add intrinsic parts directly — they bypass structural filter
    # because intrinsic name components are always specific identifiers
    for part in intrinsic_parts:
        norm = part.strip().lower()
        if norm and len(norm) >= 3 and norm not in seen:
            seen.add(norm)
            clean.append(norm)

    keyword_prefix = " ".join(clean[:40])
    skill_prefix = " ".join(skill_keywords[:20])
    augmented = keyword_prefix + "\n" + skill_prefix + "\n" + issue_text[:1500]

    return augmented, clean



# ── Keyword search ────────────────────────────────────────────────────────────

def keyword_search(keywords: list[str], conn: sqlite3.Connection,
                   top_n: int = 8) -> list[dict]:
    """
    Precision keyword search over chunk content.

    Scoring model (per chunk):
      base_score  = number of DISTINCT keywords found in content
      exact_bonus = +2 per keyword that matches with original casing
      defn_bonus  = +4 if chunk looks like a definition of any keyword
                    (matches 'def kw', 'kw(', 'static.*kw', 'kw =')
      path_bonus  = +3 if the file path contains any keyword token
      concentration = base_score^1.5 (rewards chunks hitting many kws)

    final_score = concentration + exact_bonus + defn_bonus + path_bonus

    This ensures that a file NAMED after the keyword (e.g. import.c
    containing find_frozen) scores much higher than a test file that
    merely mentions the keyword in a comment.
    """
    if not keywords:
        return []

    # Filter to code identifiers only
    code_kws = [k for k in keywords
                if ' ' not in k and 4 <= len(k) <= 60
                and re.match(r"^[\w.\-:@/]+$", k)]

    if not code_kws:
        return []

    # Pre-build lowercase versions and path tokens for all keywords
    kw_lower = [k.lower() for k in code_kws]
    # Path tokens: split each keyword on _ and camelCase
    path_tokens = set()
    for k in code_kws:
        path_tokens.add(k.lower())
        for part in re.split(r'[_\-]', k):
            if len(part) >= 3:
                path_tokens.add(part.lower())
        camel = re.findall(r'[A-Z]?[a-z]+|[A-Z]+(?=[A-Z]|$)', k)
        for part in camel:
            if len(part) >= 3:
                path_tokens.add(part.lower())

    # Definition patterns: these indicate the chunk DEFINES the identifier
    def_patterns = []
    for k in code_kws:
        kl = re.escape(k.lower())
        def_patterns.append(re.compile(
            rf'(?:^|\s)(?:def |static\s+\w+\s+|\w+\s+){kl}\s*[\({{]',
            re.MULTILINE | re.IGNORECASE
        ))
        # Also match simple assignment definitions
        def_patterns.append(re.compile(
            rf'^{kl}\s*[=(]',
            re.MULTILINE | re.IGNORECASE
        ))

    try:
        all_chunks = conn.execute(
            "SELECT id, filepath, start_line, end_line, content FROM chunks"
        ).fetchall()
    except Exception:
        return []

    scored = []
    for row in all_chunks:
        chunk_id, filepath, start, end, content = row
        content_lower = content.lower()
        filepath_lower = filepath.lower().replace("\\", "/")

        # 1. Base score: distinct keywords found in content
        kws_found = [k for k, kl in zip(code_kws, kw_lower)
                     if kl in content_lower]
        base = len(kws_found)
        if base == 0:
            continue

        # 2. Exact case bonus
        exact_bonus = sum(2 for k in kws_found if k in content)

        # 3. Definition bonus — chunk likely defines the identifier
        defn_bonus = 0
        for pat in def_patterns:
            if pat.search(content):
                defn_bonus += 4
                break  # one definition bonus per chunk is enough

        # 4. Path bonus — file path contains keyword token
        path_bonus = 0
        fp_parts = set(re.split(r'[/\\._]', filepath_lower))
        if fp_parts & path_tokens:
            path_bonus = 3

        # 5. Concentration: reward chunks that hit many different keywords
        # base^1.5 means 3 keywords scores 5.2x a single keyword, not 3x
        concentration = base ** 1.5

        final_score = concentration + exact_bonus + defn_bonus + path_bonus

        # Require 2+ distinct keyword matches to filter single-kw false positives
        # e.g. hamt.c matches only PyUnicode_AsUTF8 (1 kw) — skip it
        # import.c matches find_frozen + PyUnicode_AsUTF8 + look_up_frozen (3 kws)
        min_kws = 2 if len(code_kws) >= 3 else 1
        if base >= min_kws:
            scored.append({
                "filepath": filepath,
                "start_line": start,
                "end_line": end,
                "content": content,
                "distance": max(0.0, 1.0 - (final_score / (len(code_kws) * 10))),
                "keyword_hits": final_score,
                "source": "keyword",
            })

    scored.sort(key=lambda x: x["keyword_hits"], reverse=True)
    # Filter out documentation files — they score high on generic keywords
    # but are never fix locations. Use pattern-based detection.
    source_only = [c for c in scored if not is_doc_file(c["filepath"])]
    # If filtering removed everything, fall back to unfiltered
    results = source_only if source_only else scored
    return results[:top_n]


# ── Hybrid retrieval ──────────────────────────────────────────────────────────

def hybrid_retrieve(
    issue_text: str,
    skill_keywords: list[str],
    conn: sqlite3.Connection,
    top_k: int = TOP_K_CHUNKS,
) -> tuple[list[dict], list[str]]:
    """
    Combines vector similarity search with keyword search.
    
    Strategy:
      1. Augment query with extracted identifiers
      2. Vector search with augmented query (semantic similarity)
      3. Keyword search for exact identifier matches (precision)
      4. Merge: keyword hits get priority, vector fills remaining slots
      5. Deduplicate by (filepath, start_line)
    
    Returns (chunks, extracted_keywords) so caller can log what was extracted.
    """
    # Step 1: augment query and extract keywords
    augmented_query, extracted_kws = augment_query(issue_text, skill_keywords)

    if extracted_kws:
        console.print(
            f"[dim]Query augmented with {len(extracted_kws)} identifiers: "
            f"{', '.join(extracted_kws[:8])}"
            f"{'...' if len(extracted_kws) > 8 else ''}[/]"
        )
        # Index sanity check: use most specific (longest) identifier
        if extracted_kws:
            # Pick the longest identifier — most likely to be specific
            specific_kw = max(extracted_kws, key=len)
            try:
                hit_count = conn.execute(
                    "SELECT COUNT(*) FROM chunks WHERE content LIKE ?",
                    (f"%{specific_kw}%",)
                ).fetchone()[0]
                console.print(
                    f"[dim]  Index check: '{specific_kw}' "
                    f"appears in {hit_count} chunks[/]"
                )
            except Exception:
                pass

    # Step 2: vector search with augmented query
    vector_chunks = retrieve_chunks_vector(augmented_query, conn, top_k=top_k)

    # Step 3: keyword search
    keyword_chunks = keyword_search(extracted_kws, conn, top_n=max(12, top_k // 2))

    if keyword_chunks:
        kw_files = sorted(set(c["filepath"] for c in keyword_chunks))
        top_scores = [(c["filepath"].split("/")[-1], f"{c['keyword_hits']:.1f}")
                      for c in keyword_chunks[:5]]
        console.print(
            f"[dim]Keyword search found {len(keyword_chunks)} chunks "
            f"from: {', '.join(kw_files[:3])}"
            f"{'...' if len(kw_files) > 3 else ''}[/]"
        )
        console.print(
            f"[dim]  Top keyword scores: "
            f"{', '.join(f'{f}={s}' for f, s in top_scores)}[/]"
        )

    # Step 4: merge — keyword hits first, then vector, deduplicated
    seen = set()
    merged = []

    for chunk in keyword_chunks:
        key = (chunk["filepath"], chunk["start_line"])
        if key not in seen:
            seen.add(key)
            chunk["retrieval"] = "keyword+vector" if any(
                (c["filepath"], c["start_line"]) == key
                for c in vector_chunks
            ) else "keyword"
            merged.append(chunk)

    for chunk in vector_chunks:
        key = (chunk["filepath"], chunk["start_line"])
        if key not in seen:
            seen.add(key)
            chunk["retrieval"] = "vector"
            merged.append(chunk)

    # Cap at top_k * 1.5 to leave room for both sources
    return merged[:int(top_k * 2)], extracted_kws


def retrieve_chunks_vector(query, conn, top_k=TOP_K_CHUNKS):
    """Pure vector similarity search — renamed to make room for hybrid."""
    query_emb = embed_single(query)
    if not query_emb:
        return []
    rows = conn.execute("""
        SELECT c.filepath, c.start_line, c.end_line, c.content, ce.distance
        FROM chunk_embeddings ce
        JOIN chunks c ON c.id = ce.rowid
        WHERE ce.embedding MATCH ? AND k = ?
        ORDER BY ce.distance
    """, (vec_to_blob(query_emb), top_k)).fetchall()
    return [{"filepath": r[0], "start_line": r[1], "end_line": r[2],
             "content": r[3], "distance": r[4], "retrieval": "vector",
             "keyword_hits": 0}
            for r in rows]


def retrieve_chunks(query, conn, top_k=TOP_K_CHUNKS):
    """Legacy wrapper — used by eval harness. Pure vector search."""
    return retrieve_chunks_vector(query, conn, top_k)


def format_retrieved_chunks(chunks):
    if not chunks:
        return "(no relevant chunks retrieved)"
    seen = set()
    unique = []
    for c in chunks:
        key = (c["filepath"], c["start_line"])
        if key not in seen:
            seen.add(key); unique.append(c)
    by_file = {}
    for c in unique:
        by_file.setdefault(c["filepath"], []).append(c)

    # Score each file by its best chunk — keyword hits weighted heavily
    # This ensures high-signal files (e.g. import.c with find_frozen)
    # appear first regardless of alphabetical order, so they get into
    # the context budget before lower-signal files
    def file_score(fchunks):
        best_kw = max((c.get("keyword_hits", 0) for c in fchunks), default=0)
        best_sim = max((1 - c.get("distance", 1.0) for c in fchunks), default=0)
        fp = fchunks[0].get("filepath", "") if fchunks else ""
        # Penalise documentation files — they consume context budget without
        # providing actionable source code. Uses pattern-based detection,
        # not hardcoded project-specific names.
        doc_penalty = 0.1 if is_doc_file(fp) else 1.0
        # keyword hits dominate: a file with many keyword hits always
        # beats a file with only vector similarity
        return (best_kw * 10 + best_sim) * doc_penalty

    sorted_files = sorted(
        by_file.items(),
        key=lambda x: file_score(x[1]),
        reverse=True  # highest scoring files first
    )

    total_chars = 0
    parts = []
    n_files = len(sorted_files)
    # Per-file budget: no single file can consume more than 40% of total
    # This ensures high-scoring files like import.c always get representation
    # even if lower-ranked files have many large chunks
    PER_FILE_CAP = int(MAX_CONTEXT_CHARS * 0.40)

    for filepath, fchunks in sorted_files:
        file_chars = 0
        file_parts = []
        for c in sorted(fchunks, key=lambda x: x["start_line"]):
            retrieval_tag = c.get("retrieval", "vector")
            kw_hits = c.get("keyword_hits", 0)
            tag_str = (f"[{retrieval_tag}, {kw_hits} kw hits]"
                       if kw_hits else f"[{retrieval_tag}]")
            block = "  // lines {}-{} sim={:.2f} {}\n{}".format(
                c["start_line"], c["end_line"],
                1 - c["distance"], tag_str, c["content"])
            if total_chars + len(block) > MAX_CONTEXT_CHARS:
                break
            if file_chars + len(block) > PER_FILE_CAP:
                break
            file_parts.append(block)
            total_chars += len(block)
            file_chars += len(block)
        if file_parts:
            parts.append("### {}\n{}".format(filepath, "\n\n".join(file_parts)))
    return "\n\n".join(parts)

# ── Repo resolution ───────────────────────────────────────────────────────────

def detect_git_root(start):
    current = start.resolve()
    for parent in [current] + list(current.parents):
        if (parent / ".git").exists():
            return parent
    return None


def check_embed_model():
    try:
        r = requests.get(f"{OLLAMA_HOST}/api/tags", timeout=3)
        r.raise_for_status()
        models = [m["name"] for m in r.json().get("models", [])]
        short = EMBED_MODEL.split(":")[0].lower()
        if any(short in m.lower() for m in models):
            return True
        console.print(f"[yellow]Embed model '{EMBED_MODEL}' not found.[/]")
        console.print(f"[dim]Available: {', '.join(models)}[/]")
        console.print(f"[dim]Run: ollama pull {EMBED_MODEL}[/]")
        return False
    except requests.exceptions.Timeout:
        console.print("[yellow]Ollama timeout — using keyword fallback.[/]")
        return False
    except Exception as e:
        console.print(f"[yellow]Embed check failed ({type(e).__name__}) — keyword fallback.[/]")
        return False


def keyword_scan_fallback(repo_root, issue_text, skill_keywords, skill_contents,
                          max_files=25):
    issue_kws = extract_keywords_from_issue(issue_text)
    all_kws = list(dict.fromkeys(skill_keywords + issue_kws))
    skill_text = " ".join(skill_contents).lower()
    all_files = []
    for f in repo_root.rglob("*"):
        try:
            is_file = f.is_file()
        except (OSError, PermissionError):
            continue
        if is_file and f.suffix in INDEXABLE_EXTENSIONS:
            if any(part in SKIP_DIRS for part in f.parts):
                continue
            all_files.append(f)
    all_kws_set = {k.lower() for k in all_kws}
    scored = sorted(all_files,
                    key=lambda f: score_file(f, repo_root, all_kws_set),
                    reverse=True)
    mentioned = [f for f in scored[:max_files]
                 if f.name.lower() in skill_text
                 or f.parent.name.lower() + "/" + f.name.lower() in skill_text]
    other = [f for f in scored[:max_files] if f not in mentioned]
    content_files = (mentioned + other)[:5]
    console.print(f"[bold cyan]Keyword scan:[/] reading {len(content_files)} files")
    contents_block = ""
    total = 0
    for f in content_files:
        if total >= 24000:
            break
        rel = f.relative_to(repo_root)
        console.print(f"[dim]  {rel}[/]")
        try:
            text = f.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        lines = text.splitlines()
        numbered = "\n".join("{:4d}  {}".format(i+1, l) for i, l in enumerate(lines))
        if len(numbered) > 8000:
            numbered = numbered[:8000] + "\n...(truncated)"
        remaining = 24000 - total
        if len(numbered) > remaining:
            numbered = numbered[:remaining]
        total += len(numbered)
        contents_block += "\n### {}\n```\n{}\n```\n".format(rel, numbered)
    return "## Key File Contents (keyword scan)\n" + contents_block


def resolve_repo_context(args, issue_text, skill_contents, skill_keywords):
    if args.no_repo:
        return None, False
    repo_root = None
    if args.repo:
        repo_root = Path(args.repo).resolve()
        if not repo_root.exists():
            console.print(f"[red]--repo path does not exist: {repo_root}[/]")
            return None, False
    else:
        repo_root = detect_git_root(Path.cwd())
        if not repo_root:
            console.print("[dim]No local git repo detected.[/]")
            return None, False
        console.print(f"[dim]Auto-detected repo: {repo_root}[/]")

    if SQLITE_VEC_AVAILABLE and check_embed_model():
        index_path = get_index_path(repo_root)
        conn = open_index(index_path, create=True)
        if conn:
            init_index_schema(conn)
            needs_index = args.reindex or args.update or not index_is_fresh(conn, repo_root)
            if args.update and not args.reindex:
                # Force incremental check even if HEAD hash matches
                pass  # get_stale_files will find changed files
            if needs_index:
                # force=False when --update so incremental path is taken
                # force=True for --reindex or first-time build
                force_rebuild = args.reindex or (not args.update and not index_is_fresh(conn, repo_root))
                build_index(repo_root, conn, force=force_rebuild,
                            max_index_files=args.max_files,
                            issue_text=issue_text,
                            skill_keywords=skill_keywords)
            else:
                stored = conn.execute(
                    "SELECT value FROM meta WHERE key='total_chunks'"
                ).fetchone()
                console.print(f"[green]Using cached RAG index ({stored[0] if stored else '?'} chunks)[/]")
                # Ensure dir keyword map exists even on cache hit
                try:
                    kw_count = conn.execute(
                        "SELECT COUNT(*) FROM dir_keywords"
                    ).fetchone()[0]
                    if kw_count == 0:
                        console.print("[dim]  Building missing dir maps...[/]")
                        build_git_activity_map(repo_root, conn)
                        build_dir_keyword_map(repo_root, conn)
                except Exception:
                    build_git_activity_map(repo_root, conn)
                    build_dir_keyword_map(repo_root, conn)

            console.print("[bold cyan]Hybrid retrieval (vector + keyword)...[/]")
            chunks, extracted_kws = hybrid_retrieve(
                issue_text, skill_keywords, conn, top_k=TOP_K_CHUNKS
            )
            if chunks:
                files_found = sorted(set(c["filepath"] for c in chunks))
                kw_hits = sum(1 for c in chunks if "keyword" in c.get("retrieval",""))
                console.print(
                    f"[green]Retrieved {len(chunks)} chunks from "
                    f"{len(files_found)} files "
                    f"({kw_hits} keyword hits)[/]"
                )
                for f in files_found:
                    console.print(f"  [dim]{f}[/]")
                context = format_retrieved_chunks(chunks)
                conn.close()
                return context, True
            else:
                console.print("[yellow]Hybrid retrieval returned no chunks.[/]")
                conn.close()

    console.print("[dim]Using keyword-based file scan (no RAG).[/]")
    context = keyword_scan_fallback(repo_root, issue_text, skill_keywords, skill_contents)
    return context, False

# ── Skills ────────────────────────────────────────────────────────────────────

def load_all_skills():
    if not SKILLS_DIR.exists():
        console.print(f"[yellow]Skills folder not found: {SKILLS_DIR}[/]")
        return {}
    skills = {}
    seen = set()
    for subdir in [SKILLS_DIR / "core", SKILLS_DIR / "user", SKILLS_DIR]:
        if not subdir.exists():
            continue
        for f in subdir.glob("*.md"):
            if f.stem == "TEMPLATE" or f in seen:
                continue
            seen.add(f)
            text = f.read_text(encoding="utf-8")
            kws = _parse_trigger_keywords(text)
            skills[f.stem] = (kws, text)
    if skills:
        console.print(f"[dim]Skills found: {', '.join(sorted(skills.keys()))}[/]")
    return skills


def _parse_trigger_keywords(content):
    m = re.search(r"## Trigger keywords\s*\n(.*?)(?:\n##|\Z)", content, re.DOTALL)
    if not m:
        return []
    return [kw.strip().lower() for kw in re.split(r"[,\n]+", m.group(1).strip()) if kw.strip()]


def auto_detect_skills(issue_text, all_skills):
    text_lower = issue_text.lower()
    return [name for name, (kws, _) in all_skills.items()
            if any(kw in text_lower for kw in kws)]


def resolve_skills(issue_text, all_skills, forced, interactive):
    detected = auto_detect_skills(issue_text, all_skills)
    final_names = list(dict.fromkeys((forced or []) + detected))
    valid = set(all_skills.keys())
    final_names = [n for n in final_names if n in valid]
    if interactive:
        console.print()
        console.print(f"[bold cyan]Auto-detected skills:[/] {', '.join(final_names) or 'none'}")
        available = sorted(all_skills.keys())
        if available:
            console.print(f"[dim]Available: {', '.join(available)}[/]")
            override = Prompt.ask(
                "Skills to load (comma-separated, Enter to accept, 'none' to skip)",
                default=",".join(final_names) if final_names else "none",
            )
            if override.strip().lower() == "none":
                final_names = []
            else:
                final_names = [s.strip() for s in override.split(",") if s.strip()]
                final_names = [n for n in final_names if n in valid]
    if final_names:
        console.print(f"[green]Loading skills:[/] {', '.join(final_names)}")
    return [all_skills[n][1] for n in final_names], final_names


def get_skill_keywords(all_skills, loaded_names):
    kws = []
    for name in loaded_names:
        if name in all_skills:
            kws.extend(all_skills[name][0])
    return kws

# ── Prompts ───────────────────────────────────────────────────────────────────

BASE_SYSTEM_PROMPT = """\
You are a principal-level software engineer and debugging expert with 20+ years
of experience in LLVM, Linux kernel, GCC, CPython, and major web runtimes.

HALLUCINATION RULES:
1. FILE PATHS: Only cite paths that appear VERBATIM in the retrieved source
   section above. If a file you want to reference is not listed there, write
   [UNCERTAIN: likely in <dir> — not in retrieved source]. NEVER invent
   plausible-sounding variants of filenames (e.g. InstCombineCastUtils.cpp
   when only InstCombineCasts.cpp was retrieved).
2. FUNCTION NAMES: Only cite functions visible in the retrieved source.
   If uncertain: [UNCERTAIN: look for function named X]
3. COMMANDS: Every shell command must be syntactically correct and runnable.
4. CONFIDENCE: Label each hypothesis [HIGH], [MEDIUM], or [LOW CONFIDENCE].
5. LINE NUMBERS: Cite actual line numbers shown in the source.
6. DRAFT PATCH: Must modify lines that appear in the source. Write
   [NOT IN RETRIEVED SOURCE] if relevant code was not retrieved.

OUTPUT FORMAT:

## 1. Issue Summary
What breaks, under what conditions, observable symptom.

## 2. Root Cause Hypothesis
Specific mechanism — file, function, line region. Label confidence.

## 3. Affected Components
- Exact file path (or [UNCERTAIN])
- Specific function name
- Why implicated

## 4. Reproduction Checklist
Numbered, copy-pasteable, correct commands.

## 5. Investigation Steps
Surgical. Name exact tool/flag/function, what to look for, what it rules out.

## 6. Draft Patch
REVIEW BEFORE APPLYING — this is a starting point, not a final fix.
Unified diff format:
```diff
--- a/path/to/file
+++ b/path/to/file
@@ -LINE,COUNT +LINE,COUNT @@
 context
-removed
+added
```
Write [NOT IN RETRIEVED SOURCE] if relevant code is not present.

## 7. Verification Plan
Specific tests, locations, frameworks, assertions.

## 8. Related Issues / Prior Art
Named bug class, similar fixes, relevant engineers.

## 9. Confidence Assessment
Evaluate and state confidence for each dimension using ONLY these labels:

**Retrieval:** [HIGH | MEDIUM | LOW]
- HIGH: target file appears verbatim in retrieved source with relevant functions visible
- MEDIUM: target file retrieved but specific fix location not clearly visible
- LOW: file not in retrieved source, diagnosis based on training knowledge only

**Mechanism:** [HIGH | MEDIUM | LOW]
- HIGH: root cause confirmed by reading actual source lines
- MEDIUM: mechanism is plausible but not directly visible in retrieved source
- LOW: speculative based on issue description only

**Patch:** [HIGH | MEDIUM | LOW]
- HIGH: patch modifies lines visible in retrieved source, API calls verified
- MEDIUM: patch direction correct but line numbers approximate or API unverified
- LOW: patch is conceptual only, not grounded in retrieved source

**Recommended action:**
Based on the above, give ONE of:
- "Apply and test" — HIGH confidence across all three dimensions
- "Review logic before applying" — MEDIUM confidence in patch
- "Use as direction only — do not apply directly" — LOW confidence in patch
- "Retrieve [specific file] and re-diagnose" — file not in retrieved source
"""


def build_system_prompt(skills, repo_context, used_rag):
    prompt = ""
    if repo_context:
        method = "semantic RAG" if used_rag else "keyword scan"
        prompt += (
            "# RETRIEVED SOURCE CODE\n"
            + "=" * 60 + "\n"
            + f"Retrieved via {method}. REAL FILES WITH REAL LINE NUMBERS.\n"
            "Ground your diagnosis and patch in this source only.\n"
            + "=" * 60 + "\n\n"
            + repo_context
            + "\n\n" + "=" * 60 + "\n"
            "END OF RETRIEVED SOURCE\n"
            + "=" * 60 + "\n\n"
        )
    prompt += BASE_SYSTEM_PROMPT
    if skills:
        prompt += "\n\n---\n\n# Expert Knowledge Base\n\n"
        prompt += "\n\n".join(skills)
    return prompt


USER_TEMPLATE = """\
Diagnose the following GitHub issue and produce a draft patch.

Before writing anything:
1. Find the relevant functions in the RETRIEVED SOURCE CODE above.
2. Read their logic using the line numbers shown.
3. Identify the exact line(s) where the bug manifests.
4. Write diagnosis and patch based ONLY on what you see in the source.
5. If the fix location is not in the retrieved source, say [NOT IN RETRIEVED SOURCE].

---
{issue_text}
---
"""

# ── GitHub ────────────────────────────────────────────────────────────────────

def parse_github_url(url):
    m = re.search(r"github\.com/([^/]+)/([^/]+)/issues/(\d+)", url)
    if not m:
        raise ValueError(f"Cannot parse: {url!r}")
    return m.group(1), m.group(2), int(m.group(3))


def fetch_github_issue(url):
    owner, repo, number = parse_github_url(url)
    headers = {"Accept": "application/vnd.github+json"}
    if GITHUB_TOKEN:
        headers["Authorization"] = f"Bearer {GITHUB_TOKEN}"
    with console.status("[bold cyan]Fetching issue from GitHub...[/]"):
        resp = requests.get(
            f"https://api.github.com/repos/{owner}/{repo}/issues/{number}",
            headers=headers, timeout=15)
        resp.raise_for_status()
        data = resp.json()
        comments = requests.get(data["comments_url"], headers=headers,
                                timeout=15).json()
    parts = [
        f"Repository: {owner}/{repo}",
        f"Issue #{number}: {data['title']}",
        f"State: {data['state']}",
        f"Labels: {', '.join(l['name'] for l in data.get('labels', [])) or 'none'}",
        "", "## Issue Body", data.get("body") or "(no body)",
    ]
    if comments:
        parts.append("\n## Comments (up to 5)")
        for c in comments[:5]:
            parts.append(f"\n**@{c['user']['login']}:**\n{c['body']}")
    return "\n".join(parts)

# ── Ollama ────────────────────────────────────────────────────────────────────

def check_ollama():
    try:
        r = requests.get(f"{OLLAMA_HOST}/api/tags", timeout=5)
        r.raise_for_status()
        models = [m["name"] for m in r.json().get("models", [])]
    except requests.exceptions.ConnectionError:
        console.print(f"[bold red]Cannot reach Ollama at {OLLAMA_HOST}[/]")
        sys.exit(1)
    short = OLLAMA_MODEL.split(":")[0]
    if not any(short in m for m in models):
        console.print(f"[yellow]Model {OLLAMA_MODEL} not found.[/]")
        console.print(f"Pull it:  ollama pull {OLLAMA_MODEL}")
        sys.exit(1)


def stream_diagnosis(issue_text, system_prompt):
    payload = {
        "model": OLLAMA_MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": USER_TEMPLATE.format(issue_text=issue_text)},
        ],
        "stream": True,
        # qwen3-coder-next has 256K context but needs more VRAM per token
    # Use a smaller context on first attempt, fall back if it fails
    "options": {"temperature": 0.15, "num_predict": 4096, "num_ctx": 8192},
    }
    console.print()
    console.print(Rule(f"[bold cyan]Diagnosis + Draft Patch  {OLLAMA_MODEL}"))
    console.print()
    full_response = []
    with requests.post(f"{OLLAMA_HOST}/api/chat", json=payload,
                       stream=True, timeout=600) as resp:
        if not resp.ok:
            console.print(f"[red]Ollama error {resp.status_code}: {resp.text[:500]}[/]")
            resp.raise_for_status()
        buffer = ""
        for raw_line in resp.iter_lines():
            if not raw_line:
                continue
            try:
                chunk = json.loads(raw_line)
            except json.JSONDecodeError:
                continue
            token = chunk.get("message", {}).get("content", "")
            if token:
                full_response.append(token)
                buffer += token
                if "\n" in buffer:
                    lines = buffer.split("\n")
                    for line in lines[:-1]:
                        console.print(line)
                    buffer = lines[-1]
            if chunk.get("done"):
                if buffer:
                    console.print(buffer)
                break
    diagnosis = "".join(full_response)
    return diagnosis


def validate_confidence(diagnosis, repo_context):
    """Post-generation external confidence check."""
    if not repo_context:
        return diagnosis

    import re as _re

    cited_files = set()
    # Match filenames in backticks, diff headers, File: citations
    for pat in [
        r'`([^`\n]{3,80}\.[ch](?:pp?)?)`',
        r'--- a/([^\n]+\.[ch](?:pp?)?)',
        r'File[:\s*]+([^\n`\s]+\.[ch](?:pp?)?)',
    ]:
        cited_files.update(_re.findall(pat, diagnosis))

    if not cited_files:
        return diagnosis

    retrieved_files = set(_re.findall(r'### ([^\n]+\.[ch](?:pp?)?)', repo_context))

    hallucinated = []
    for cited in cited_files:
        cited_name = cited.strip().split('/')[-1]
        if not any(cited_name in rf for rf in retrieved_files):
            close = [rf for rf in retrieved_files
                     if cited_name[:12].lower() in rf.lower()]
            hallucinated.append((cited, close))

    if not hallucinated:
        return diagnosis

    lines = [
        '', '---', '## Automated Retrieval Warning', '',
        'The following files cited in this diagnosis were **not present** '
        'in the retrieved source chunks. They may be correct (cited from '
        'model training knowledge) or hallucinated:', '',
    ]
    for cited, close in hallucinated:
        lines.append(f'- `{cited}` — NOT IN RETRIEVED CHUNKS')
        if close:
            close_str = ', '.join(f'`{c}`' for c in close[:3])
            lines.append(f'  - Similar retrieved files: {close_str}')
    lines += [
        '', '**Recommended action:**',
        '- Verify all cited files exist in your local repo before applying',
        '- If a similar file was retrieved above, check whether the cited',
        '  file is a variant or correct',
        '- Treat unverified citations as direction only, not confirmed fixes',
    ]
    return diagnosis + '\n' + '\n'.join(lines)



# ── Input / Output ────────────────────────────────────────────────────────────

def read_paste():
    console.print("[dim]Paste issue text, then Ctrl-D (Mac/Linux) or Ctrl-Z+Enter (Windows):[/]")
    lines = []
    try:
        while True:
            lines.append(input())
    except EOFError:
        pass
    return "\n".join(lines)


def get_issue_text(args):
    if args.url:
        return fetch_github_issue(args.url)
    if args.text:
        return open(args.text, encoding="utf-8").read()
    if args.paste:
        return read_paste()
    console.print("  [bold]1[/] GitHub URL  [bold]2[/] Paste  [bold]3[/] File")
    choice = Prompt.ask("Choice", choices=["1","2","3"], default="1")
    if choice == "1":
        return fetch_github_issue(Prompt.ask("GitHub issue URL"))
    elif choice == "2":
        return read_paste()
    else:
        return open(Prompt.ask("File path"), encoding="utf-8").read()


def print_banner(skill_count, rag_available):
    rag_status = "RAG ready" if rag_available else "RAG unavailable (keyword fallback)"
    console.print(Panel.fit(
        f"[bold cyan]issue_doctor[/]  [dim]local AI bug diagnosis + draft patch[/]\n"
        f"[dim]model: {OLLAMA_MODEL}   embed: {EMBED_MODEL}   "
        f"skills: {skill_count}   {rag_status}[/]",
        border_style="cyan",
    ))
    console.print()


def save_report(diagnosis, issue_text, skill_names, used_rag):
    if Prompt.ask("\nSave report?", choices=["y","n"], default="n") == "y":
        filename = Prompt.ask("Filename", default=f"diagnosis_{int(time.time())}.md")
        with open(filename, "w", encoding="utf-8") as f:
            f.write("# Issue Doctor Report\n\n")
            f.write(f"**Skills:** {', '.join(skill_names) or 'none'}\n")
            f.write(f"**Retrieval:** {'RAG (semantic)' if used_rag else 'keyword scan'}\n\n")
            f.write("## Original Issue\n\n```\n")
            f.write(issue_text[:3000])
            f.write("\n```\n\n## Diagnosis + Draft Patch\n\n")
            f.write(diagnosis)
        console.print(f"[green]Saved to [bold]{filename}[/][/]")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    global OLLAMA_MODEL, OLLAMA_HOST, EMBED_MODEL

    parser = argparse.ArgumentParser(description="Local AI bug diagnosis + draft patch.")
    parser.add_argument("--url",       metavar="URL")
    parser.add_argument("--text",      metavar="FILE")
    parser.add_argument("--paste",     action="store_true")
    parser.add_argument("--model",     metavar="NAME")
    parser.add_argument("--host",      metavar="URL")
    parser.add_argument("--embed",     metavar="NAME")
    parser.add_argument("--skills",    metavar="NAMES")
    parser.add_argument("--no-skills", action="store_true")
    parser.add_argument("--repo",      metavar="PATH")
    parser.add_argument("--no-repo",   action="store_true")
    parser.add_argument("--reindex",   action="store_true")
    parser.add_argument("--update",    action="store_true",
                        help="Incrementally update index with changed files only")
    parser.add_argument("--max-files", type=int, default=3000, metavar="N")
    parser.add_argument("--diagnose",  action="store_true")
    parser.add_argument("--no-save",   action="store_true",
                        help="Skip save prompt (for scripted use)")
    parser.add_argument("--save-to",   metavar="FILE",
                        help="Save diagnosis to this file directly")
    args = parser.parse_args()

    if args.model:  OLLAMA_MODEL = args.model
    if args.host:   OLLAMA_HOST  = args.host
    if args.embed:  EMBED_MODEL  = args.embed

    if args.diagnose:
        console.print("[bold cyan]issue_doctor diagnostics[/]")
        console.print(f"  OLLAMA_HOST:  {OLLAMA_HOST}")
        console.print(f"  OLLAMA_MODEL: {OLLAMA_MODEL}")
        console.print(f"  EMBED_MODEL:  {EMBED_MODEL}")
        console.print(f"  SKILLS_DIR:   {SKILLS_DIR}")
        console.print(f"  sqlite-vec:   {'available' if SQLITE_VEC_AVAILABLE else 'NOT available'}")
        try:
            r = requests.get(f"{OLLAMA_HOST}/api/tags", timeout=3)
            models = [m["name"] for m in r.json().get("models", [])]
            console.print(f"  Ollama:       reachable")
            console.print(f"  Models:       {', '.join(models) or 'none'}")
            embed_short = EMBED_MODEL.split(":")[0].lower()
            model_short = OLLAMA_MODEL.split(":")[0].lower()
            console.print(f"  Embed model:  {'FOUND' if any(embed_short in m.lower() for m in models) else 'NOT FOUND'}")
            console.print(f"  Diag model:   {'FOUND' if any(model_short in m.lower() for m in models) else 'NOT FOUND'}")
        except Exception as e:
            console.print(f"  Ollama:       ERROR - {e}")
        sys.exit(0)

    all_skills = {} if args.no_skills else load_all_skills()
    rag_available = SQLITE_VEC_AVAILABLE and check_embed_model()
    print_banner(len(all_skills), rag_available)
    check_ollama()

    issue_text = get_issue_text(args)
    if not issue_text.strip():
        console.print("[red]No issue text provided.[/]")
        sys.exit(1)

    console.print()
    console.print(Panel(
        issue_text[:600] + ("..." if len(issue_text) > 600 else ""),
        title="[bold]Issue (preview)[/]", border_style="dim",
    ))

    forced = [s.strip() for s in args.skills.split(",")] if args.skills else None
    is_interactive = not (args.url or args.text or args.paste)
    skill_contents, skill_names = resolve_skills(
        issue_text, all_skills, forced, is_interactive)
    skill_keywords = get_skill_keywords(all_skills, skill_names)

    repo_context, used_rag = resolve_repo_context(
        args, issue_text, skill_contents, skill_keywords)

    system_prompt = build_system_prompt(skill_contents, repo_context, used_rag)
    diagnosis = stream_diagnosis(issue_text, system_prompt)
    diagnosis = validate_confidence(diagnosis, repo_context)

    if args.save_to:
        with open(args.save_to, "w", encoding="utf-8") as f:
            f.write(diagnosis)
    elif not args.no_save:
        save_report(diagnosis, issue_text, skill_names, used_rag)
    console.print()
    console.print(Rule("[dim]Done[/]"))


if __name__ == "__main__":
    main()